2025-01-02 21:03:35,349 - DEBUG - Falling back to TensorFlow client; we recommended you install the Cloud TPU client directly with pip install cloud-tpu-client.
2025-01-02 21:03:35,802 - DEBUG - Creating converter from 7 to 5
2025-01-02 21:03:35,802 - DEBUG - Creating converter from 5 to 7
2025-01-02 21:03:35,803 - DEBUG - Creating converter from 7 to 5
2025-01-02 21:03:35,803 - DEBUG - Creating converter from 5 to 7
2025-01-02 21:03:37,677 - DEBUG - CACHEDIR=C:\Users\sajad\.matplotlib
2025-01-02 21:03:37,682 - DEBUG - Using fontManager instance from C:\Users\sajad\.matplotlib\fontlist-v330.json
2025-01-02 21:03:39,932 - DEBUG - Starting new HTTPS connection (1): huggingface.co:443
2025-01-02 21:03:40,134 - DEBUG - https://huggingface.co:443 "HEAD /ProsusAI/finbert/resolve/main/config.json HTTP/1.1" 200 0
2025-01-02 21:03:45,341 - WARNING - From C:\Users\sajad\AppData\Local\Programs\Python\Python310\lib\site-packages\tf_keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

2025-01-02 21:03:46,012 - DEBUG - https://huggingface.co:443 "HEAD /ProsusAI/finbert/resolve/main/model.safetensors HTTP/1.1" 404 0
2025-01-02 21:03:46,842 - DEBUG - https://huggingface.co:443 "HEAD /facebook/bart-large-cnn/resolve/main/config.json HTTP/1.1" 200 0
2025-01-02 21:03:48,297 - DEBUG - https://huggingface.co:443 "HEAD /facebook/bart-large-cnn/resolve/main/generation_config.json HTTP/1.1" 200 0
2025-01-02 21:03:49,558 - WARNING - From C:\Users\sajad\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\src\backend\common\global_state.py:82: The name tf.reset_default_graph is deprecated. Please use tf.compat.v1.reset_default_graph instead.

2025-01-02 21:03:51,895 - DEBUG - Falling back to TensorFlow client; we recommended you install the Cloud TPU client directly with pip install cloud-tpu-client.
2025-01-02 21:03:52,186 - DEBUG - Creating converter from 7 to 5
2025-01-02 21:03:52,186 - DEBUG - Creating converter from 5 to 7
2025-01-02 21:03:52,186 - DEBUG - Creating converter from 7 to 5
2025-01-02 21:03:52,186 - DEBUG - Creating converter from 5 to 7
2025-01-02 21:03:56,992 - WARNING - From C:\Users\sajad\AppData\Local\Programs\Python\Python310\lib\site-packages\tf_keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

2025-01-02 21:03:58,415 - DEBUG - Starting new HTTPS connection (1): huggingface.co:443
2025-01-02 21:03:58,579 - DEBUG - https://huggingface.co:443 "HEAD /ProsusAI/finbert/resolve/main/config.json HTTP/1.1" 200 0
2025-01-02 21:03:58,852 - DEBUG - https://huggingface.co:443 "HEAD /ProsusAI/finbert/resolve/main/model.safetensors HTTP/1.1" 404 0
2025-01-02 21:03:59,310 - WARNING - From C:\Users\sajad\AppData\Local\Programs\Python\Python310\lib\site-packages\tf_keras\src\backend.py:873: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

2025-01-02 21:04:00,558 - DEBUG - Creating converter from 3 to 5
2025-01-02 21:04:01,669 - DEBUG - https://huggingface.co:443 "HEAD /facebook/bart-large-cnn/resolve/main/config.json HTTP/1.1" 200 0
2025-01-02 21:04:03,646 - DEBUG - https://huggingface.co:443 "HEAD /facebook/bart-large-cnn/resolve/main/generation_config.json HTTP/1.1" 200 0
2025-01-02 21:04:05,330 - DEBUG - https://huggingface.co:443 "GET /api/models/ProsusAI/finbert HTTP/1.1" 200 4496
2025-01-02 21:04:05,468 - DEBUG - https://huggingface.co:443 "GET /api/models/ProsusAI/finbert/commits/main HTTP/1.1" 200 4974
2025-01-02 21:04:05,608 - DEBUG - https://huggingface.co:443 "GET /api/models/ProsusAI/finbert/discussions?p=0 HTTP/1.1" 200 12033
2025-01-02 21:04:05,811 - DEBUG - https://huggingface.co:443 "GET /api/models/ProsusAI/finbert/commits/refs%2Fpr%2F10 HTTP/1.1" 200 5939
2025-01-02 21:04:05,812 - DEBUG - Starting new HTTPS connection (1): safetensors-convert.hf.space:443
2025-01-02 21:04:06,079 - DEBUG - https://safetensors-convert.hf.space:443 "POST /call/run HTTP/1.1" 503 58
2025-01-02 21:04:07,478 - DEBUG - Starting new HTTPS connection (1): api.tavily.com:443
2025-01-02 21:04:07,959 - DEBUG - https://api.tavily.com:443 "POST /v1/search HTTP/1.1" 404 22
2025-01-02 21:04:07,960 - ERROR - HTTP error occurred: 404 Client Error: Not Found for url: https://api.tavily.com/v1/search
2025-01-02 21:04:07,962 - ERROR - Error: HTTP error occurred: 404 Client Error: Not Found for url: https://api.tavily.com/v1/search
2025-01-02 21:04:10,733 - ERROR - Error querying Firestore: The default Firebase app does not exist. Make sure to initialize the SDK by calling initialize_app().
2025-01-02 21:04:10,734 - ERROR - Error: The default Firebase app does not exist. Make sure to initialize the SDK by calling initialize_app().
2025-01-02 21:04:24,054 - ERROR - Error: generate_rag_response() missing 1 required positional argument: 'documents'
2025-01-02 21:05:18,568 - DEBUG - Starting new HTTPS connection (1): api.tavily.com:443
2025-01-02 21:05:19,023 - DEBUG - https://api.tavily.com:443 "POST /v1/search HTTP/1.1" 404 22
2025-01-02 21:05:19,024 - ERROR - HTTP error occurred: 404 Client Error: Not Found for url: https://api.tavily.com/v1/search
2025-01-02 21:05:19,024 - ERROR - Error: HTTP error occurred: 404 Client Error: Not Found for url: https://api.tavily.com/v1/search
2025-01-02 21:05:25,596 - DEBUG - Starting new HTTPS connection (1): api.tavily.com:443
2025-01-02 21:05:26,082 - DEBUG - https://api.tavily.com:443 "POST /v1/search HTTP/1.1" 404 22
2025-01-02 21:05:26,083 - ERROR - HTTP error occurred: 404 Client Error: Not Found for url: https://api.tavily.com/v1/search
2025-01-02 21:05:26,084 - ERROR - Error: HTTP error occurred: 404 Client Error: Not Found for url: https://api.tavily.com/v1/search
